name: ricinvestors
description: An application for RIC Investors


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^0.4.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^4.0.2
  shared_preferences: ^0.5.3+4
  firebase_auth: ^0.14.0+1
  google_sign_in: ^4.0.6
  firebase_database: ^3.0.7
  get_it: ^1.0.3+2
  provider: ^3.0.0+1
  cloud_firestore:
  flushbar: ^1.9.0
  flutter_launcher_icons: ^0.7.2+1



  font_awesome_flutter: "8.5.0"





dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"


flutter:
 uses-material-design: true


 fonts:
   - family: Ubuntu
     fonts:
       - asset: fonts/Ubuntu-Regular.ttf
       - asset: fonts/Ubuntu-Bold.ttf

   - family: SF-Pro-Text-Regular
     fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf

   - family: SF-Pro-Text-Bold
     fonts:
        - asset: fonts/SF-Pro-Text-Bold.otf

   - family: Calibre-Semibold
     fonts:
           - asset: fonts/Calibre Semibold.otf

   - family: CustomIcons
     fonts:
           - asset: fonts/custom_icons.ttf

   - family: CustomIcons1
     fonts:
           - asset: fonts/CustomIcons.ttf

   - family: Poppins-Bold
     fonts:
           - asset: fonts/Poppins-Bold.ttf

   - family: Poppins-Medium
     fonts:
           - asset: fonts/Poppins-Medium.ttf




 assets:
   - assets/properties.json
   - images/profile_header_background.png
   - assets/image_01.png
   - assets/image_02.jpg
   - assets/image_03.jpg
   - assets/image_04.jpg
   - assets/image01.png
   - assets/image02.png
   - assets/logo.png

